# Generated by Django 3.0.8 on 2020-10-25 08:07

import BlogApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeruser',
            name='profileImage',
            field=models.ImageField(null=True, upload_to=BlogApp.models.upload_to),
        ),
    ]
