# Generated by Django 3.0.8 on 2020-10-27 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0004_auto_20201027_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postDate',
            field=models.DateField(auto_now=True),
        ),
    ]
