# Generated by Django 3.0.8 on 2020-10-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApp', '0007_auto_20201028_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='comment_post',
        ),
    ]
